<?php
$z[0]=Array("cfg_basehost","",122,142);
$z[1]=Array("cfg_basehost","",234,254);
$z[2]=Array("include","",407,444);
$z[2][4]['filename']="header.htm";
$z[3]=Array("cfg_basehost","",528,548);
$z[4]=Array("field","",658,679);
$z[4][4]['name']="content";
$z[5]=Array("list","\r\n						<a href=\"[field:arcurl/]\">\r\n							<div class=\"news_item\">							\r\n								<h2>[field:title/]</h2>		\r\n								<div class=\"news_text\">\r\n									<img src=\"[field:picname/]\" alt=\"\" class=\"newsImg\" />\r\n									<div class=\"news_content\">\r\n										<h3>[field:pubdate function=\"MyDate('20y-m-d',@me)\"/]</h3>\r\n										<p>[field:description function='cn_substr(@me,300)'/]...</p>\r\n									</div>\r\n								</div>								\r\n							</div>\r\n						</a>\r\n						",838,1334);
$z[5][4]['pagesize']="5";
$z[6]=Array("pagelist","",1437,1529);
$z[6][4]['pagelang']="en";
$z[6][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",1613,1651);
$z[7][4]['filename']="rtSider.htm";
$z[8]=Array("include","",1737,1774);
$z[8][4]['filename']="footer.htm";
$z[9]=Array("cfg_basehost","",1825,1845);

?>