<?php
$z[0]=Array("cfg_basehost","",118,138);
$z[1]=Array("cfg_basehost","",229,249);
$z[2]=Array("include","",398,435);
$z[2][4]['filename']="header.htm";
$z[3]=Array("cfg_basehost","",516,536);
$z[4]=Array("field","",643,664);
$z[4][4]['name']="content";
$z[5]=Array("list","\n						<div class=\"news_item\">\n							<a href=\"[field:arcurl/]\">\n								<h2>[field:title/]</h2>		\n								<div class=\"news_text\">\n									<img src=\"[field:picname/]\" alt=\"\" class=\"newsImg\" />\n									<div class=\"news_content\">\n										<h3>[field:pubdate function=\"MyDate('20y-m-d',@me)\"/]</h3>\n										<p>[field:description function='cn_substr(@me,300)'/]...</p>\n									</div>\n								</div>\n							</a>	\n						</div>	\n						",818,1288);
$z[5][4]['pagesize']="5";
$z[6]=Array("pagelist","",1385,1477);
$z[6][4]['pagelang']="en";
$z[6][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",1555,1593);
$z[7][4]['filename']="rtSider.htm";
$z[8]=Array("include","",1673,1710);
$z[8][4]['filename']="footer.htm";
$z[9]=Array("cfg_basehost","",1758,1778);

?>