<?php
$z[0]=Array("field","",39,67);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",107,136);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n			        <a href=\"[field:typeurl/]\">\r\n			        	<li class=\"childContentLi\">[field:typename/]</li>\r\n			        </a> \r\n			        ",204,391);
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";
$z[3]=Array("global","",450,477);
$z[3][4]['name']="cfg_basehost";

?>