<div class="news_item">
							<a href="[field:arcurl/]">
								<h2>[field:title/]</h2>		
								<div class="news_text">
									<img src="[field:picname/]" alt="" class="newsImg" />
									<div class="news_content">
										<h3>[field:pubdate function="MyDate('20y-m-d',@me)"/]</h3>
										<p>[field:description function='cn_substr(@me,300)'/]...</p>
									</div>
								</div>
							</a>	
						</div>