<?php
$z[0]=Array("cfg_basehost","",45,65);
$z[1]=Array("cfg_basehost","",201,221);
$z[2]=Array("cfg_basehost","",285,305);
$z[3]=Array("channelartlist","\r\n				<li class=\"nav_lev1\">\r\n					<a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n					<div class=\"dh\">\r\n						<ul class=\"nav_ul2\">\r\n							{dede:channel type='son' noself='yes'} \r\n							<li class=\"nav_lev2\">\r\n								<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n							</li>\r\n							{/dede:channel}\r\n						</ul>\r\n					</div>\r\n				</li>\r\n				",478,914);
$z[3][4]['typeid']="1,2,3,5,4";

?>