<?php
$z[0]=Array("cfg_basehost","",122,142);
$z[1]=Array("cfg_basehost","",241,261);
$z[2]=Array("cfg_basehost","",401,421);
$z[3]=Array("cfg_basehost","",509,529);
$z[4]=Array("cfg_basehost","",690,710);
$z[5]=Array("cfg_basehost","",779,799);
$z[6]=Array("cfg_basehost","",968,988);
$z[7]=Array("channelartlist","\r\n    					<li class=\"nav_lev1\">\r\n							<a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n    						<div class=\"dh\">\r\n	    						<ul class=\"nav_ul2\">\r\n	    							{dede:channel type='son' noself='yes'} \r\n	    							<li class=\"nav_lev2\">\r\n	    								<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n	    							</li>\r\n	    							{/dede:channel}\r\n	    						</ul>\r\n    						</div>\r\n    					</li>\r\n    					",1037,1535);
$z[7][4]['typeid']="1,2,3,5,4";
$z[8]=Array("cfg_basehost","",1921,1941);
$z[9]=Array("cfg_basehost","",2496,2516);
$z[10]=Array("cfg_basehost","",2932,2952);
$z[11]=Array("cfg_basehost","",3100,3120);
$z[12]=Array("cfg_basehost","",3268,3288);
$z[13]=Array("cfg_basehost","",3436,3456);
$z[14]=Array("cfg_basehost","",3604,3624);
$z[15]=Array("cfg_basehost","",3904,3924);
$z[16]=Array("cfg_basehost","",4501,4521);
$z[17]=Array("arclist","\r\n    						<li>\r\n    							<a class=\"title\" href=\"[field:arcurl/]\">\r\n    								<span class=\"lab\">></span>\r\n    								[field:title/]\r\n    								<span class=\"date\">[[field:pubdate function=MyDate('Y-m-d',@me)/]]</span>\r\n    							</a>\r\n    						</li>\r\n    						",4644,4986);
$z[17][4]['row']="3";
$z[17][4]['titlelen']="80";
$z[17][4]['typeid']="5";
$z[17][4]['orderby']="hot";
$z[18]=Array("cfg_basehost","",5093,5113);
$z[19]=Array("cfg_basehost","",5309,5329);
$z[20]=Array("cfg_basehost","",5386,5406);
$z[21]=Array("cfg_basehost","",5512,5532);
$z[22]=Array("cfg_basehost","",5588,5608);
$z[23]=Array("include","",5777,5814);
$z[23][4]['filename']="footer.htm";
$z[24]=Array("cfg_basehost","",5949,5969);
$z[25]=Array("cfg_basehost","",6070,6090);

?>